"""Configuration system for :mod:`glide` (typed schema + YAML/CLI loading)."""

from .loader import (
    apply_overrides,
    build_training_args,
    deep_merge,
    dict_to_dataclass,
    load_config,
    version_output_dir,
)
from .schema import (
    GlideConfig,
    DataConfig,
    EvalConfig,
    GenerationConfig,
    LoggingConfig,
    Modality,
    ModelConfig,
    PackingConfig,
    PeftConfigSpec,
    RewardSpec,
    RLConfig,
    SpecialTokensConfig,
    SpeechConfig,
    SpeechTask,
    Task,
    TemplateConfig,
    VisionConfig,
)

__all__ = [
    "GlideConfig",
    "DataConfig",
    "EvalConfig",
    "GenerationConfig",
    "LoggingConfig",
    "Modality",
    "ModelConfig",
    "PackingConfig",
    "PeftConfigSpec",
    "RLConfig",
    "RewardSpec",
    "SpecialTokensConfig",
    "SpeechConfig",
    "SpeechTask",
    "Task",
    "TemplateConfig",
    "VisionConfig",
    "load_config",
    "deep_merge",
    "apply_overrides",
    "dict_to_dataclass",
    "build_training_args",
    "version_output_dir",
]
